### ISSUE TITLE
Correciones

### ISSUE THREAD

**Issue by AlvaroMartinFernandez** [4GeeksAcademy/AndresVillani00-InstagramPost-91#1]
Buenas tardes,

Necesito que realices las siguienes correcciones.

- [ ] Que pongas el background negro 
- [ ] si te fijas el conetino esta desbordado todo es por que has puesto un margin del 35 % en cada lado si quieres centrar el contenido horizontalmente puedes utilizar el `margin:0 auto` 
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/d2e23e5d-11b1-412f-b9b9-2b387e3c988c">

- [ ] Por ultimo los iconos compartir y html5 necesito que los centres verticalmente

Si tienes cualquier duda me puedes preguntar

**Comment by AndresVillani00** [comment]
Vale entiendo, se puede entregar otra vez con las correcciones?, y nada siempre me pasa lo mismo con css en mi monitor se veia perfecto pero entiendo cual es el error

**Comment by AlvaroMartinFernandez** [comment]
Ahora esta muchísimo mejor, si me imaginaba que en tu monitor se veria perfecto a partir de la practica 3 teneis que hacer todo responsive y tener cuidado por que no esperar que todo el mundo tenga la misma pantalla o definicion,
